stages:
  - build
  - test

default:
  name: pipeline
  docker:
    registry: docker.io
  
    
build:
  stage: build
  script: 
    - echo "Building"
  
test:
  stage: test
  script: 
    - echo "Testing"