stages:
  - build
  - test

default:
  docker:
    registry: docker.io
    image: openjdk:17-jdk-slim
  paths:
    - app/build/reports/*
  
    
build:
  stage: build
  script: 
    - echo "Building"
  docker:
    registry: dockerhub.io
    image: openjdk:21-jdk-slim
  
test:
  stage: test
  script: 
    - echo "Testing"